# Generated by Django 5.2.4 on 2025-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='answer',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='question',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='is_from_user',
            field=models.BooleanField(default=True),
        ),
    ]
