# Generated by Django 5.2.4 on 2025-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chathistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokvideo',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
