# Generated by Django 5.2.4 on 2025-07-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tiktokvideo_cover_url_tiktokvideo_download_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiktokvideo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tiktokvideo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ'), ('PROCESSING', 'Đang xử lý'), ('COMPLETE', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
