# Generated by Django 5.2.4 on 2025-08-08 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chathistory_options_alter_tiktokvideo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, verbose_name='URL Gốc')),
                ('tracking_id', models.CharField(blank=True, max_length=15, unique=True, verbose_name='ID Theo dõi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Link Theo dõi',
                'verbose_name_plural': 'Các Link Theo dõi',
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Dấu thời gian')),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.trackinglink', verbose_name='Link Theo dõi')),
            ],
            options={
                'verbose_name': 'Nhật ký Vị trí',
                'verbose_name_plural': 'Các Nhật ký Vị trí',
            },
        ),
    ]
