# Generated by Django 5.2.4 on 2025-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trackinglink_locationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglink',
            name='require_consent',
            field=models.BooleanField(default=False, verbose_name='Bắt buộc cấp quyền'),
        ),
    ]
