# Generated by Django 5.2.4 on 2025-09-17 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trackinglink_require_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trackinglink',
            options={},
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_scraped', models.URLField(max_length=2000)),
                ('fields_extracted', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('json_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('csv_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('md_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
