# Generated by Django 5.2.4 on 2025-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_locationlog_options_alter_trackinglink_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperesult',
            old_name='cost',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='scraperesult',
            old_name='url_scraped',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='scraperesult',
            name='csv_file_path',
        ),
        migrations.RemoveField(
            model_name='scraperesult',
            name='fields_extracted',
        ),
        migrations.RemoveField(
            model_name='scraperesult',
            name='json_file_path',
        ),
        migrations.RemoveField(
            model_name='scraperesult',
            name='md_file_path',
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='csv_result',
            field=models.FileField(blank=True, null=True, upload_to='scrape_results/'),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='fields',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='json_result',
            field=models.FileField(blank=True, null=True, upload_to='scrape_results/'),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='model',
            field=models.CharField(default='gemini-1.5-flash', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ'), ('PROCESSING', 'Đang xử lý'), ('COMPLETE', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20),
        ),
    ]
