# Generated by Django 5.0.6 on 2025-09-23 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_cost_scraperesult_total_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['timestamp'], 'verbose_name': 'Chat History', 'verbose_name_plural': 'Chat Histories'},
        ),
        migrations.AlterModelOptions(
            name='locationlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Location Log', 'verbose_name_plural': 'Location Logs'},
        ),
        migrations.AlterModelOptions(
            name='scraperesult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tiktokvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'TikTok Video', 'verbose_name_plural': 'TikTok Videos'},
        ),
        migrations.AlterModelOptions(
            name='trackinglink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tracking Link', 'verbose_name_plural': 'Tracking Links'},
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='predicted_views',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lượt xem dự đoán'),
        ),
        migrations.AddField(
            model_name='tiktokvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Theo dõi'),
        ),
    ]
