# Generated by Django 5.2.6 on 2025-10-01 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_chathistory_options_alter_locationlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Chat Histories'},
        ),
        migrations.AlterModelOptions(
            name='locationlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Location Logs'},
        ),
        migrations.AlterModelOptions(
            name='scraperesult',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Scrape Results'},
        ),
        migrations.AlterModelOptions(
            name='tiktokvideo',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'TikTok Videos'},
        ),
        migrations.AlterModelOptions(
            name='trackinglink',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tracking Links'},
        ),
        migrations.RemoveField(
            model_name='tiktokvideo',
            name='predicted_views',
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='tracking_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.trackinglink'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='fields',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='model',
            field=models.CharField(default='gemini-1.5-flash-latest', max_length=50),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='comments',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='likes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='play_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='shares',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='require_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
