# Generated by Django 5.2.4 on 2025-10-01 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_chathistory_options_alter_locationlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['timestamp'], 'verbose_name': 'Lịch sử trò chuyện', 'verbose_name_plural': 'Lịch sử trò chuyện'},
        ),
        migrations.AlterModelOptions(
            name='locationlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Nhật ký vị trí', 'verbose_name_plural': 'Các nhật ký vị trí'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterModelOptions(
            name='scraperesult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kết quả Scrape', 'verbose_name_plural': 'Các kết quả Scrape'},
        ),
        migrations.AlterModelOptions(
            name='tiktokvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video TikTok', 'verbose_name_plural': 'Các Video TikTok'},
        ),
        migrations.AlterModelOptions(
            name='trackinglink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Link theo dõi', 'verbose_name_plural': 'Các link theo dõi'},
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=5, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='tracking_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.trackinglink', verbose_name='Link theo dõi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Tiểu sử'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='csv_result',
            field=models.FileField(blank=True, null=True, upload_to='scrape_results/csv/', verbose_name='Kết quả CSV'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Thông báo lỗi'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='fields',
            field=models.CharField(max_length=1024, verbose_name='Các trường cần lấy'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='input_tokens',
            field=models.IntegerField(default=0, verbose_name='Input Tokens'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='json_result',
            field=models.FileField(blank=True, null=True, upload_to='scrape_results/json/', verbose_name='Kết quả JSON'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model AI'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='output_tokens',
            field=models.IntegerField(default=0, verbose_name='Output Tokens'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ'), ('PROCESSING', 'Đang xử lý'), ('COMPLETE', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='PENDING', max_length=15, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='Tổng chi phí'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='url',
            field=models.URLField(max_length=2048, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Kết quả phân tích'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt bình luận'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL Tải về'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Thời lượng (giây)'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt thích'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='shares',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt chia sẻ'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ'), ('PROCESSING', 'Đang xử lý'), ('COMPLETE', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='PENDING', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Bản ghi lời thoại'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_videos', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID Video'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_url',
            field=models.URLField(max_length=1024, verbose_name='URL Video'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='original_url',
            field=models.URLField(max_length=2048, verbose_name='URL Gốc'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='require_consent',
            field=models.BooleanField(default=False, verbose_name='Yêu cầu đồng ý'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Theo dõi'),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
